#!/bin/bash
hive -e "
 select '$1' as date,
        weekly_navigation_count.project as project,
        navigation_count_total / view_count_total as percent_interlanguage_navigation

   from (select concat(current_project, '.', project_family) as project,
                sum(navigation_count) as navigation_count_total
           from wmf.interlanguage_navigation
          where date between '$1' and '$2'
            and project_family in ('wikipedia', 'wikivoyage', 'wikisource')
          group by project_family, current_project
        ) weekly_navigation_count

            inner join
        (select project,
                sum(view_count) as view_count_total

           from wmf.projectview_hourly
          where concat(year, '-', lpad(month, 2, '0'), '-', lpad(day, 2, '0')) between '$1' and '$2'
            and access_method = 'desktop'
            and agent_type = 'user'
            and (   project like '%wikipedia'
                or  project like '%wikivoyage'
                or  project like '%wikisource'
                )
          group by project
        ) weekly_projectview                    on weekly_navigation_count.project = weekly_projectview.project
;
" 2> /dev/null | grep -v parquet.hadoop
